apiVersion: v1
kind: Secret
metadata:
  name: influxdb-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  influxdburl: {{ (.Values.influxdb.url) | b64enc | quote }} 
  influxdbauth: {{ (.Values.influxdb.auth) | b64enc | quote }}
  bucket: {{ (.Values.influxdb.bucket) | b64enc | quote }} 
  org: {{ (.Values.influxdb.org) | b64enc | quote }}
