{{ if .Values.db.backup.enabled }}
apiVersion: v1
data:
kind: Secret
metadata:
  name: s3-creds
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.db.backup.key | b64enc | quote }}
  ACCESS_SECRET_KEY: {{ .Values.db.backup.secret | b64enc | quote }} 
{{ end }}
