{{ if or .Values.miraximporter.deploy .Values.viewer.deploy }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name}}-htpasswd
data:
  htpasswd: {{ htpasswd .Values.miraximporter.auth.user ( .Values.miraximporter.auth.password | toString )  | b64enc | quote }}
  auth: {{ printf "%s:%s" .Values.miraximporter.auth.user  ( .Values.miraximporter.auth.password | toString )  | b64enc | quote }}
{{ end }}
