{{ if .Values.miraximporter.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mirax-importer
spec:
  selector:
    app: {{ .Release.Name }}-mirax-importer
  ports:
    - port: 8081
      name: web
      targetPort: 8081
{{ end }}
