apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-cnpg-network-policy
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ .Release.Name }}-{{ .Values.db.dbname }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: cloudnativepg
