{{ if not .Values.data.createPVC  }}
{{ if .Values.data.storageClass }} 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Gi
  storageClassName: {{ .Values.data.storageClass }}
{{ end }}
{{ end }}
