namespace:

cronjob:
  schedule: "0 8 * * *" # UTC
  ttlSecondsAfterFinished: 10800 # 3h
  image: cerit.io/cerit/hubresguard:08-09-2022-1
  jhNamespace: "jupyterhub-ns" # namespace where jupyterHub is deployed
  cluster: "kuba"
  sender: "" 
  queryTime: "86400" # 24h
  gpuMaxDays: "3"
  cpuMaxDays: "10"

prometheus:
  credentialsDir: "/mnt/prometheus/" # trailing slash is important!
  username: # plaintext
  password: # plaintext
  promaddr: # plaintext


