{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_resource_request, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(container_resource_request{namespace=~\"$namespace\"}) by (pod))"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{resource=\"nvidia_com_gpu\",namespace=~\"$namespace\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) / sum(container_resource_request{namespace=~\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"memory\"}) / sum(container_resource_request{namespace=~\"$namespace\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) / sum(container_resource_limit{namespace=~\"$namespace\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"memory\"}) / sum(container_resource_limit{namespace=~\"$namespace\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "GPU Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\", resource=\"cerit.io/gpu-mem\"}) or vector(0)"
    }
   ]
  },
  { "title": "Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Request Quota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_quota{type=\"request\", resource=\"cpu\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Request Quota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_quota{type=\"request\", resource=\"memory\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Limit Quota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_quota{type=\"limit\", resource=\"cpu\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Limit Quota",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_quota{type=\"limit\", resource=\"memory\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Request Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\", resource=\"cpu\"}) by (namespace) / on(namespace) namespace_quota{type=\"request\", resource=\"cpu\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Request Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\", resource=\"memory\"}) by (namespace) / on(namespace) namespace_quota{type=\"request\", resource=\"memory\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Limit Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\", resource=\"cpu\"}) by (namespace) / on(namespace) namespace_quota{type=\"limit\", resource=\"cpu\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Limit Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\", resource=\"memory\"}) by (namespace) / on(namespace) namespace_quota{type=\"limit\", resource=\"memory\", namespace=~\"$namespace\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\",resource=\"cpu\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) by (container, pod, namespace) / sum(container_resource_request{namespace=~\"$namespace\",resource=\"cpu\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\",resource=\"cpu\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"cpu\"}) by (container, pod, namespace) / sum(container_resource_limit{namespace=~\"$namespace\",resource=\"cpu\"}) by (container, pod, namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", container!=\"\", resource=\"memory\"}) by (pod)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"memory\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_request{namespace=~\"$namespace\",resource=\"memory\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"memory\"}) by (container, pod, namespace) / sum(container_resource_request{namespace=~\"$namespace\",resource=\"memory\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_limit{namespace=~\"$namespace\",resource=\"memory\"}) by (container, pod, namespace)"
    },
    {
     "expr": "sum(container_resource_usage{namespace=~\"$namespace\", resource=\"memory\"}) by (container, pod, namespace) / sum(container_resource_limit{namespace=~\"$namespace\",resource=\"memory\"}) by (container, pod, namespace)"
    }
   ]
  }
 ]
}