apiVersion: v1
kind: Secret
metadata:
  name: personal-monitoring-prometheus-url
stringData:
  url: "http://{{- $.Release.Name }}-prometheus-{{- $.Values.prometheus.server.name }}.{{- $.Release.Namespace }}.svc.cluster.local"
