apiVersion: batch/v1
kind: CronJob
metadata:
  name: hubresourcesguard-cj
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: "Forbid"
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      backoffLimit: 1
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
          - name: hubresguard
            image: {{ .Values.cronjob.image }} 
            imagePullPolicy: IfNotPresent
            command:
            - "hubresguard" 
            env:
              - name: "NAMESPACE"
                value: {{ .Values.cronjob.userNamespace | quote }} 
              - name: "CLUSTER"
                value: {{ .Values.cronjob.cluster | quote }} 
              - name: "CREDS_DIR"
                value: {{ .Values.prometheus.credentialsDir | quote }}
              - name: "SENDER"
                value: {{ .Values.cronjob.sender | quote }}
              - name: "HELO"
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: "QUERY_TIME"
                value: {{ .Values.cronjob.queryTime | quote }}
              - name: "GPU_MAX_DAYS"
                value: {{ .Values.cronjob.gpuMaxDays | quote }}
              - name: "CPU_MAX_DAYS"
                value: {{ .Values.cronjob.cpuMaxDays | quote }}
              - name: "INFLUXDB_PATH"
                value: {{ .Values.influx.credentialsDir | quote }}
            volumeMounts:
              - mountPath: {{ .Values.prometheus.credentialsDir | quote }}
                name: prometheus-secret
                readOnly: true
              - name: influx-secret
                mountPath: {{ .Values.influx.credentialsDir | quote }}
                readOnly: true
          restartPolicy: OnFailure
          serviceAccount: hubresguard-sa
          securityContext:
            runAsUser: 1000
          volumes:
            - name: prometheus-secret
              secret:
                secretName: prometheus-credentials
            - name: influx-secret
               secret:
                 secretName: influx-credentials
