apiVersion: v1
kind: Secret
metadata:
  name: prometheus-credentials
  namespace: {{ .Values.namespace }} 
type: Opaque
data:
  username: {{ (.Values.prometheus.username) | b64enc | quote }}
  password: {{ (.Values.prometheus.password) | b64enc | quote }}
  promaddr: {{ (.Values.prometheus.promaddr) | b64enc | quote }}
