apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.name }}-certificate
  dnsNames:
    - {{ .Values.name }}-svc
    - {{ .Values.name }}-svc.{{ .Values.namespace }}
    - {{ .Values.name }}-svc.{{ .Values.namespace }}.svc
  issuerRef:
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
