apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}-configuration.cerit.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.name }}-certificate
webhooks:
- name: {{ .Values.name }}-webhook.cerit.io
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ .Values.name }}-svc
      namespace: {{ .Values.namespace }}
      path: {{ .Values.webhook.path }}
  failurePolicy: Ignore # Defaults to Fail
  matchPolicy: Exact    # Defaults to Equivalent
  rules:
  - apiGroups:
    {{- range .Values.webhook.apiGroups }}
    - {{ . | quote }}
    {{- end }}
    apiVersions:
    {{- range .Values.webhook.apiVersions }}
    - {{ . | quote }}
    {{- end }}
    operations:
    {{- range .Values.webhook.operations }}
    - {{ . | quote }}
    {{- end }}
    resources:
    {{- range .Values.webhook.resources }}
    - {{ . | quote }}
    {{- end }}
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
