apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-role
rules:
  - apiGroups: [ ""]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list"]
  - apiGroups: [ "networking.k8s.io"]
    resources: [ "ingresses" ]
    verbs: [ "get", "watch", "list" ]
