apiVersion: v1
kind: ConfigMap
metadata:
  name: ceritsc-master-webconfig
  {{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
data:
  webconfig.yaml: |
    basic_auth_users:
      {{ (htpasswd .Values.global.prometheusUser .Values.global.prometheusPassword | replace ":" ": ") }}
