apiVersion: v1
kind: Secret
metadata:
  name: ceritsc-loki-auth
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
   auth: {{ (htpasswd .Values.global.lokiUser .Values.global.lokiPassword) | b64enc | quote }}

