apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}-configuration.cerit.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.name }}-certificate
webhooks:
  - name: {{ .Values.name }}-webhook.cerit.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    clientConfig:
      service:
        name: {{ .Values.name }}-svc
        namespace: {{ .Values.namespace }}
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"

