apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"] # PODS/STATUS
    verbs: ["get", "watch", "list", "patch", "create"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-sa
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
