kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: {{ .Values.name }}-app
  name: {{ .Values.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: {{ .Values.name }}-app
