apiVersion: v2
name: xopat
version: 0.4.4
appVersion: 0.1
description: A Helm chart for deploying explainable open pathology analysis tool (xopat)
type: application
maintainers:
- name: CERIT-SC
  email: root@cerit-sc.cz
