{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_usage:irate:5m{mode=\"utilized\",cluster=~\"$cluster\",unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_usage{mode=\"utilized\",cluster=~\"$cluster\",unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_disk_usage{mode=\"utilized\",cluster=~\"$cluster\",unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_usage:irate:5m{cluster=~\"$cluster\",mode=\"utilized\",unit=\"core\"}"
    }
   ]
  },
  {
   "title": "CPU Total (computed from metrics)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_total{cluster=~\"$cluster\",unit=\"core\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_usage{cluster=~\"$cluster\",mode=\"utilized\",unit=\"byte\"}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_total{cluster=~\"$cluster\",unit=\"byte\"}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_disk_usage{cluster=~\"$cluster\",mode=\"utilized\",unit=\"byte\"}",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_disk_total{cluster=~\"$cluster\",unit=\"byte\"}",
     "legendFormat": "join-less"
    }
   ]
  },
  {
   "title": "CPU Usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodes_cpu_usage{cluster=~\"$cluster\", unit=\"percentage\", mode=\"utilized\", type=\"system\"}",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Memory Usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodes_memory_usage{cluster=~\"$cluster\", mode=\"utilized\", type=\"system\", unit=\"percentage\"}",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Disk Usage (percentage)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nodes_disk_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"percentage\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "nodes_cpu_usage{cluster=~\"$cluster\", unit=\"cores\", mode=\"utilized\", type=\"system\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Memory Usage (byte)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodes_memory_usage{cluster=~\"$cluster\", mode=\"utilized\", type=\"system\", unit=\"bytes\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Disk Usage (byte)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodes_disk_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"byte\"}",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  }
 ]
}