{
 "title": "Kubernetes / Scheduler",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"kube-scheduler\",cluster=~\"$cluster\"}, instance)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Scheduling Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scheduler_e2e_scheduling_duration_seconds_count:node{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}[10m])) by (node)",
     "legendFormat": "{{node}} e2e"
    },
    {
     "expr": "sum(rate(scheduler_binding_duration_seconds_count:node{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (node)",
     "legendFormat": "{{node}} binding"
    },
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_count:node{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (node)",
     "legendFormat": "{{node}} scheduling algorithm"
    },
    {
     "expr": "sum(rate(scheduler_volume_scheduling_duration_seconds_count{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Scheduling latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\",cluster=~\"$cluster\"}[10m])) by (instance, le))",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_volume_scheduling_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\",cluster=~\"$cluster\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"2..\",cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"3..\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"4..\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"5..\",cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", verb=\"POST\",cluster=~\"$cluster\"}[10m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", verb=\"GET\",cluster=~\"$cluster\"}[10m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-scheduler\", instance=~\"$instance\",cluster=~\"$cluster\"}[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-scheduler\",instance=~\"$instance\",cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}