{
 "title": "Log info",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes operations",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{source=\"promtail\",cluster=~\"$cluster\",container=\"kube-apiserver\"} |= \"delete\" |= \"authorization.k8s.io/reason\" | json | annotations_authorization_k8s_io_reason != \"\" | annotations_authorization_k8s_io_decision = \"allow\" | objectRef_name != \"\" | line_format \"❌ {{TrimRight .objectRef_resource \\\"s\\\"}} {{.objectRef_name}} DELETED due to authorization from {{.impersonatedUser_username}}{{if contains \\\"to ServiceAccount\\\" .annotations_authorization_k8s_io_reason}}Service Account{{end}}{{if contains \\\"to User.*system:kube\\\" .annotations_authorization_k8s_io_reason}}Kube System{{end}}\"",
     "legendFormat": "{{objectRef_name}} - {{annotations_authorization_k8s_io_reason}}"
    },
    {
     "expr": "{source=\"promtail\",cluster=~\"$cluster\",container=\"kube-apiserver\"} |= \"create\" |= \"authorization.k8s.io/reason\" | json | annotations_authorization_k8s_io_reason != \"\" | annotations_authorization_k8s_io_decision = \"allow\" | objectRef_name != \"\" | line_format \"✅ {{TrimRight .objectRef_resource \\\"s\\\"}} {{.objectRef_name}} CREATED due to authorization from {{.impersonatedUser_username}}{{if contains \\\"to ServiceAccount\\\" .annotations_authorization_k8s_io_reason}}Service Account{{end}}{{if contains \\\"to User.*system:kube\\\" .annotations_authorization_k8s_io_reason}}Kube System{{end}}\""
    }
   ]
  },
  {
   "title": "Segfaulting programs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", cluster=~\"$cluster\"} |= \"segfault\" | regexp \"(?P<program>.*)\\\\[(?P<pid>[0-9]+)\\\\].*\" | line_format \"⚠️ Program \\\"{{.program}}\\\" with PID {{.pid}} has ended due to SEGFAULT\""
    }
   ]
  },
  {
   "title": "OOM processes",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{source=\"promtail\", job=\"systemd-journal\", cluster=~\"$cluster\"} |= \"oom-kill:\" | regexp \".*task_memcg..[^/]*.(?P<pod>[^/]+).*task=(?P<task>.+),pid=(?P<pid>[0-9]+),uid=(?P<uid>[0-9]+)\" | line_format \"☠️ Process \\\"{{.task}}\\\" with PID {{.pid}} (run under UID {{.uid}}) in pod \\\"{{.pod}}\\\" was killed by oom-kill\""
    }
   ]
  }
 ]
}