{
 "title": "Overview / Workload",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "workload",
    "label": "workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=~\"$cluster\"}, workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\",workload=~\"$workload\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\",workload=~\"$workload\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\",workload=~\"$workload\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod:kube_pod_info:workload:schedulable{workload=~\"$workload\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{resource=\"cerit_io_gpu_count\",workload=~\"$workload\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(workload_cpu_usage:schedulable{cluster=~\"$cluster\", workload=~\"$workload\", unit=\"core\"}) / sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(workload_memory_usage:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",unit=\"byte\"}) / sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(workload_cpu_usage:schedulable{cluster=~\"$cluster\", workload=~\"$workload\", unit=\"core\"}) / sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(workload_memory_usage:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",unit=\"byte\"}) / sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{resource=\"rdma_hca\",workload=~\"$workload\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{resource=\"cerit_io_gpu_mem\",workload=~\"$workload\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"cpu\",unit=\"core\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}) by (container, pod, workload) / sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"cpu\",unit=\"core\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"cpu\",unit=\"core\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}) by (container, pod, workload) / sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"cpu\",unit=\"core\"}) by (container, pod, workload)"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total:workload{workload=~\"$workload\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total:workload{workload=~\"$workload\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total:workload{workload=~\"$workload\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total:workload{workload=~\"$workload\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\", container!=\"\"}) by (pod)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\",unit=\"byte\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload) / sum(kube_pod_container_resource_requests:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\",unit=\"byte\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\",unit=\"byte\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload) / sum(kube_pod_container_resource_limits:running:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",resource=\"memory\",unit=\"byte\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_rss:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_cache:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_swap:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\",container!=\"\"}) by (container, pod, workload)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[10m])) by (workload)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[10m])) by (workload)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[10m])) by (workload)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[5m])) by (workload)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[5m])) by (workload)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[5m])) by (workload)"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total:workload:schedulable{cluster=~\"$cluster\", workload=~\"$workload\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}