{
 "title": "Overview / Node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kubernetes_node_schedulable{cluster=~\"$cluster\"}, kubernetes_node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU (From metrics)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"rdma_hca\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"ephemeral_storage\",node=~\"$node\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_count\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU (memory)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_mem\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage (system)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\", mode=\"utilized\", unit=\"cores\", type=\"system\"}) / ignoring(unit, type, mode) sum(nodes_cpu_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Usage (system)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_memory_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"bytes\", type=\"system\", kubernetes_node=~\"$node\"}) / ignoring(mode, unit, type) sum(nodes_memory_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (containers)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"cores\", type=\"containers\", kubernetes_node=~\"$node\"}) / ignoring(unit, type, mode) sum(nodes_cpu_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Usage (containers)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_memory_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"bytes\", type=\"containers\", kubernetes_node=~\"$node\"}) / ignoring(mode, unit, type) sum(nodes_memory_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_disk_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\", mode=\"utilized\", unit=\"byte\"}) / sum(nodes_disk_total{cluster=~\"$cluster\", kubernetes_node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{instance=~\"$node\",cluster=~\"$cluster\"}) / sum(kube_node_status_capacity{resource=\"pods\",node=~\"$node\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{kubernetes_node=~\"$node\", fstype!=\"\", fstype!=\"tmpfs\", cluster=~\"$cluster\"}) by (device, kubernetes_node))"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_requests{cluster=~\"$cluster\",node=~\"$node\",unit=\"cores\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nodes_memory_requests{cluster=~\"$cluster\",node=~\"$node\"}) / sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"rdma_hca\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0))/(sum(kube_node_status_allocatable{resource=\"rdma_hca\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  {
   "title": "GPUs (whole) Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_count\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0))/ (sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_count\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  {
   "title": "GPUs (memory) Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_mem\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0))/ (sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_mem\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  { "title": "Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",node=~\"$node\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",node=~\"$node\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\",node=~\"$node\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod:kube_pod_info{node=~\"$node\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_count\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\", unit=\"cores\", mode=\"utilized\", type=\"containers\"}) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodes_memory_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\", unit=\"bytes\", mode=\"utilized\", type=\"containers\"}) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodes_cpu_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\", unit=\"cores\", mode=\"utilized\", type=\"containers\"}) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodes_memory_usage{cluster=~\"$cluster\", kubernetes_node=~\"$node\",unit=\"bytes\", mode=\"utilized\", type=\"containers\"}) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"rdma_hca\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_mem\",node=~\"$node\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU (Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (cores)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", node=~\"$node\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", node=~\"$node\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", node=~\"$node\"}) by (container, pod, namespace) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\", node=~\"$node\"}) by (container, pod, namespace) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{instance=~\"$node\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{instance=~\"$node\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{instance=~\"$node\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{instance=~\"$node\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory (Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", node=~\"$node\", container!=\"\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", node=~\"$node\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_rss{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_cache{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_swap{cluster=~\"$cluster\", node=~\"$node\",container!=\"\"}) by (container, pod, namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network (Pods)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", instance=~\"$node\", pod != \"\"}[10m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", instance=~\"$node\", pod != \"\"}[10m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[10m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[10m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[10m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\", instance=~\"$node\", pod!=\"\"}[5m])) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk (Nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{kubernetes_node=~\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{kubernetes_node}} {{device}} read"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{kubernetes_node=~\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{kubernetes_node}} {{device}} written"
      },
      {
       "expr": "rate(node_disk_io_time_seconds_total{kubernetes_node=~\"$node\", device=~\"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$cluster\"}[10m])",
       "legendFormat": "{{kubernetes_node}} {{device}} io time"
      }
     ]
    },
    {
     "title": "Disk Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(\n  max by (device, kubernetes_node) (\n    node_filesystem_size_bytes{kubernetes_node=~\"$node\", fstype!=\"\", cluster=~\"$cluster\"}\n  -\n    node_filesystem_avail_bytes{kubernetes_node=~\"$node\", fstype!=\"\", cluster=~\"$cluster\"}\n  )\n) by (kubernetes_node)\n",
       "legendFormat": "used {{kubernetes_node}}"
      },
      {
       "expr": "sum(\n  max by (device, kubernetes_node) (\n    node_filesystem_avail_bytes{kubernetes_node=~\"$node\", fstype!=\"\", cluster=~\"$cluster\"}\n  )\n) by (kubernetes_node)\n",
       "legendFormat": "available {{kubernetes_node}}"
      }
     ]
    }
   ]
  }
 ]
}