{
 "title": "Overview / Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Resource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU (Hardware)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_total:hardware{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU (From metrics)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_total{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_total{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"rdma_hca\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Ephemeral Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"ephemeral_storage\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU (memory)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_mem\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU (system) Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_usage:irate:5m{cluster=~\"$cluster\", mode=\"utilized\", unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "RAM (system) Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_memory_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "CPU (containers) Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) / ignoring(unit,job,cluster,fedscrape) cluster_cpu_total{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "RAM (containers) Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\"}) / ignoring(unit,job,cluster,fedscrape) cluster_memory_total{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Node storage Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_disk_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"percentage\"}"
    }
   ]
  },
  {
   "title": "Pod usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_pods_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"pods\"}) / sum(node_pods_total{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{fstype!=\"\", fstype!=\"tmpfs\", cluster=~\"$cluster\"}) by (device, kubernetes_node))"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\",  cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"rdma_hca\",cluster=~\"$cluster\"}) or vector(0))/(sum(kube_node_status_allocatable{resource=\"rdma_hca\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  {
   "title": "GPUs (whole) Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"nvidia_com_gpu\",cluster=~\"$cluster\"}) or vector(0))/ (sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  {
   "title": "GPUs (memory) Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_mem\",cluster=~\"$cluster\"}) or vector(0))/ (sum(kube_node_status_allocatable{resource=\"cerit_io_gpu_mem\",cluster=~\"$cluster\"}) or vector(1))"
    }
   ]
  },
  { "title": "Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_pods_usage{cluster=~\"$cluster\", mode=\"utilized\", unit=\"pods\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"nvidia_com_gpu\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu_usage{cluster=~\"$cluster\", unit=\"core\"}) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory_usage{cluster=~\"$cluster\", unit=\"byte\"}) / sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu_usage{cluster=~\"$cluster\", unit=\"core\"}) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory_usage{cluster=~\"$cluster\", unit=\"byte\"}) / sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"rdma_hca\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running{resource=\"cerit_io_gpu_mem\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  { "title": "API and Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "API Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=~\"$cluster\"}[10m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress Controller Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"reading\", cluster=~\"$cluster\"})",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"waiting\", cluster=~\"$cluster\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"writing\", cluster=~\"$cluster\"})",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"accepted\", cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(ceil(increase(nginx_ingress_controller_nginx_process_connections_total{state=\"handled\", cluster=~\"$cluster\"}[5m])))",
     "legendFormat": "Handled"
    }
   ]
  },
  { "title": "Pod and Deployment Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{cluster=~\"$cluster\"} > 0) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\", phase!=\"Running\", phase!=\"Succeeded\"} > 0) by (pod, namespace, phase)",
     "legendFormat": "{{pod}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Deployments without desired replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "node_deployment_without_desired_replicas{cluster=~\"$cluster\"}",
     "legendFormat": "{{deployment}} ({{namespace}})"
    },
    {
     "expr": "node_daemonset_without_desired_replicas{cluster=~\"$cluster\"}",
     "legendFormat": "{{daemonset}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Pod",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage per Namespace",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(delta(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container!=\"\"}[$__range])) by (namespace)",
       "legendFormat": "{{namespace}}"
      },
      {
       "expr": "sum(sum_over_time(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", resource=\"cpu\"}[$__range]) * 120) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$cluster\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_cpu_requests_usage{cluster=~\"$cluster\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_cpu_limits_usage{cluster=~\"$cluster\"}) by (container, pod, namespace)"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod, namespace) /sum(increase(container_cpu_cfs_periods_total{container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod, namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", container!=\"\"}) by (pod)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~\"$cluster\", container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running{cluster=~\"$cluster\", resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_memory_requests_usage{cluster=~\"$cluster\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running{cluster=~\"$cluster\", resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_memory_limits_usage{cluster=~\"$cluster\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_rss{cluster=~\"$cluster\", container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_cache{cluster=~\"$cluster\", container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_swap{cluster=~\"$cluster\", container!=\"\"}) by (container, pod, namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=~\"$cluster\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=~\"$cluster\"}[5m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=~\"$cluster\"}[5m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=~\"$cluster\"}[5m])) by (namespace)"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}