{
 "title": "Overview / Namespace",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\",namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\",namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory limits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\",namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod:kube_pod_info:schedulable{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:schedulable{resource=\"cerit_io_gpu_count\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\", unit=\"core\"}) / sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",unit=\"byte\"}) / sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_cpu_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\", unit=\"core\"}) / sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization (from requests)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(namespace_memory_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",unit=\"byte\"}) / sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "RDMA/HCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:schedulable{resource=\"rdma_hca\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "GPU Memory (GB)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests:running:schedulable{resource=\"cerit_io_gpu_mem\",namespace=~\"$namespace\",cluster=~\"$cluster\"}) or vector(0)"
    }
   ]
  },
  { "title": "Namespace stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Namespace details ",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{cluster=~\"$cluster\"}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{cluster=~\"$cluster\"}) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "Deployments without desired replicas",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas{cluster=~\"$cluster\", kubernetes_namespace=~\"$namespace\"}/kube_deployment_spec_replicas{cluster=~\"$cluster\", kubernetes_namespace=~\"$namespace\"} < 1) by (deployment, namespace)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_cpu_requests_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_cpu_limits_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (container, pod, namespace)"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total:schedulable{namespace=~\"$namespace\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total:schedulable{namespace=~\"$namespace\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)",
       "legendFormat": "{{pod}} - {{container}}"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=~\"$namespace\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod) /sum(increase(container_cpu_cfs_periods_total{namespace=~\"$namespace\", container!=\"POD\", container!=\"\", cluster=~\"$cluster\"}[5m])) by (container, pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (w/o cache)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\", container!=\"\"}) by (pod)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_memory_requests_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits:running:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"}) by (container, pod, namespace)"
      },
      {
       "expr": "max(container_memory_limits_usage:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_rss:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_cache:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",container!=\"\"}) by (container, pod, namespace)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_memory_swap:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\",container!=\"\"}) by (container, pod, namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])) by (namespace)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[5m])) by (namespace)"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total:schedulable{cluster=~\"$cluster\", namespace=~\"$namespace\"}[10m])) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}