{
 "title": "Overview / Prometheus",
 "tags": [ "prometheus-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(prometheus_build_info, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=~\"$cluster\"}, instance)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Prometheus Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Stats",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (job, instance, version, cluster) (prometheus_build_info{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"})"
    },
    {
     "expr": "max by (job, instance, cluster) (time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\", cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}[5m])) by (scrape_job, cluster) * 1e3",
     "legendFormat": "{{cluster}} - {{scrape_job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "Targets - {{cluster}}"
    }
   ]
  },
  { "title": "Retrieval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Average Scrape Interval Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_sum{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}[5m]) / rate(prometheus_target_interval_length_seconds_count{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}[5m]) * 1e3",
     "legendFormat": "{{cluster}} {{interval}} configured"
    }
   ]
  },
  {
   "title": "Scrape failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, cluster) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} exceeded sample limit: {{job}}"
    },
    {
     "expr": "sum by (job, cluster) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} duplicate timestamp: {{job}}"
    },
    {
     "expr": "sum by (job, cluster) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} out of bounds: {{job}}"
    },
    {
     "expr": "sum by (job, cluster) (rate(prometheus_target_scrapes_sample_out_of_order_total{cluster=~\"$cluster\"}[5m]))",
     "legendFormat": "{{cluster}} out of order: {{job}}"
    }
   ]
  },
  {
   "title": "Appended Samples",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Head Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}} {{instance}} head series"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}} {{instance}} head chunks"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_duration_seconds_count{job=~\"$job\",instance=~\"$instance\",slice=\"inner_eval\", cluster=~\"$cluster\"}[5m])",
     "legendFormat": "{{cluster}} {{instance}}"
    }
   ]
  },
  {
   "title": "Stage Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (slice, cluster) (prometheus_engine_query_duration_seconds{quantile=\"0.9\",job=~\"$job\",instance=~\"$instance\", cluster=~\"$cluster\"}) * 1e3",
     "legendFormat": "{{cluster}} {{slice}}"
    }
   ]
  }
 ]
}