apiVersion: v1
data:
{{- if and .Values.db.password (ne (.Values.db.password | toString ) "") }}
  password: {{ .Values.db.password | b64enc | quote }}
{{- else }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace ( printf "%s-db-app" .Values.db.name )) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
#{{- $password := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
{{- $password := (get $secretData "password") }}
  password: {{ $password | quote }}
{{- end }}
  username: {{ .Values.db.owner | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.db.name }}-db-app
  annotations:
    "helm.sh/resource-policy": "keep"
type: kubernetes.io/basic-auth
